baseURL: "https://fabric-selects.github.io/"
languageCode: "en-us"
title: "Fabric Selects"
enableEmoji: true
markup:
  goldmark:
    extensions:
       typographer: true
    renderer:
       unsafe: true
taxonomies:
  user: users
  dependency: dependencies
  group: groups
